### ISSUE TITLE
Missing REPL Usage docs

### ISSUE THREAD

**Issue by mathpunk** [metasoarous/toto#7]
The link for `view!` is dead. A naive call of `(toto/view! [:div [:h1 "some text"]]` did not appear to get me a live browser. Can I help with documentation here?

**Comment by metasoarous** [comment]
Thanks for the notification @mathpunk!

What system are you running on? It should open up a browser. Are there any more logs in relation to this you can share?

**Comment by mathpunk** [comment]
Took me a couple weeks to get back to this. I guess it was a hiccup, everything is running fine now. The link in the README, https://github.com/metasoarous/toto#repl-usage, still has no target. But I don't need those docs to continue!

**Comment by metasoarous** [comment]
Great! Glad you're unblocked. Will try to fix up that link soon though.

Thanks again!
